### ISSUE TITLE
std.parseJson with invalid input is killing process

### ISSUE THREAD

**Issue by safareli** [hanazuki/node-jsonnet#95]
Code like `std.parseJson("$%^&")` will result with this log in console:
```
Something went wrong during jsonnet_evaluate_snippet, please report this: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: 'd'
```

and process will get killed.

Instead promise should be rejected. so one can handle this in `catch` instead of process shutting down.

related https://github.com/google/jsonnet/issues/680

**Comment by safareli** [comment]
Let me know If I can help with this

**Comment by hanazuki** [comment]
Thanks for your report.

The process seems to be killed by an uncaught exception thrown by the JSON parser used in libjsonnet. libjsonnet is responsible for catching the exception from its underlying components and returning the error to the consumer (node-jsonnet in this case) via `&error` variable.

So this problem should be fixed in libjsonnet. I'll leave a comment on the upstream tracker.

**Comment by hanazuki** [comment]
Fix is merged to libjsonnet

**Comment by safareli** [comment]
Thanks!
